### ISSUE TITLE
Add button to sansec.watch

### ISSUE THREAD

**Issue by peterjaap** [integer-net/magento2-sansec-watch#5]
Could you add a button around here;

![image](https://github.com/user-attachments/assets/d870c7ce-a74b-495e-8c53-e1406e01a5b6)

That opens `https://sansec.watch/d/<id>` when the ID is available?

**Comment by renttek** [comment]
Sure! 

Any preference over the styling & wording of the action?

Otherwise I think I'd go with one of those two:
<img width="300" alt="Screenshot 2024-11-30 at 13 35 58" src="https://github.com/user-attachments/assets/2658a92c-7095-45bf-9917-2083938ce81e">
<img width="300" alt="Screenshot 2024-11-30 at 13 36 12" src="https://github.com/user-attachments/assets/b9a51ef3-169e-44f9-b393-e6ed2d9bca14">

**Comment by peterjaap** [comment]
@renttek both are fine! But I like the button more :)
